export const SET_CATEGORIES = 'SET_CATEGORIES';
export const START_FETCHING_CATEGORIES = 'START_FETCHING_CATEGORIES';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUHT_FAILED = 'AUHT_FAILED';
export const AUTH_LOGOUT_START = 'AUTH_LOGOUT_START';
export const AUTH_LOGOUT_FAILED = 'AUTH_LOGOUT_FAILED';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_RESTRICTED_ROUTE = 'AUTH_RESTRICTED_ROUTE';

export const REGISTER_CUSTOMER_INIT = 'REGISTER_CUSTOMER_INIT';
export const REGISTER_CUSTOMER_SUCCESS = 'REGISTER_CUSTOMER_SUCCESS';
export const REGISER_CUSTOMER_FAILURE = 'REGISER_CUSTOMER_FAILURE';

export const PRODUCTS_FETCH_INIT = 'PRODUCTS_FETCH_INIT';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_FAILURE = 'PRODUCT_FETCH_FAILURE';
export const PRODUCT_CLEAR = 'PRODUCT_CLEAR';
export const PRODUCT_FETCH_SINGLE = 'PRODUCT_FETCH_SINGLE';
export const PRODUCT_FETCH_SINGLE_SUCCESS = 'PRODUCT_FETCH_SINGLE_SUCCESS';
export const PRODUCT_FETCH_SINGLE_FAILURE = 'PRODUCT_FETCH_SINGLE_FAILURE';

export const REVIEW_FETCH_INIT = 'REVIEW_FETCH_INIT';
export const REVIEW_FETCH_SUCCESS = 'REVIEW_FETCH_SUCCESS';
export const REVIEW_RESET = 'REVIEW_RESET';